### ISSUE TITLE
Allow ±

### ISSUE THREAD

**Issue by garrison** [oxinabox/Expr2LaTeX.jl#1]
Hi there,

It would be great if ± were supported as a binary operation in Expr2LaTeX.

I considered adding it to the list [here](https://github.com/oxinabox/Expr2LaTeX.jl/blob/ac0aaeb07728ebe6b00313949115af260b8266df/src/expr2math.jl#L8), but was unsure how to get this to output correct LaTeX ("\pm").

**Comment by oxinabox** [comment]
I believe adding it to the Dict above: https://github.com/oxinabox/Expr2LaTeX.jl/blob/ac0aaeb07728ebe6b00313949115af260b8266df/src/expr2math.jl#L5
```
const binops_renames =Dict( :(<=) => "\\le",
                                             :(>=) => "\\ge",
                                             :in => "\\in",
                                             :±=> "\\pm"
)
```

should do it

**Comment by garrison** [comment]
That was actually the first thing I tried, but I get

```julia
julia> to_latex(to_math(:(3±2)))
"(3 ± 2)"
```

**Comment by oxinabox** [comment]
Fixed it, turns out that `binops_renames` isn't used.
I must have either rewritten the code that should use it, or forgotten to include it in the first place.
